[discord]
    enabled = true

    [discord.webhook]
    id = 1280552491590877195
    token = "pezy4PASMsH4S_E7XEcuwMMFZYC56rUXheGpPS8fYINJZpHpwxuO9qoMzqQ4X0V9MoV5"


[player_event]
    always_trigger = false
    username_triggerlist = ["steam9", "Hen_Kok", "Fargry", "praymag", "BlackSauron", "undefined", "Prototype", "Edwin1Cleef", "Bronepoezd", "SamCcp", "aleksandr88", "ZoomLock", "DemonsSlayer", "Wildogina", "NewDeSenYch", "LoraKroff", "VovaBrogg", "Phoenix", "1Yowskak1", "NoobScope", "zaxar333", "Nebro", "SpaceBack", "RasulxMix", "xFlakex", "doniwko", "Dallr0g", "Nikitos666LoL", "CrashTest", "Vallirion", "frikaGames", "Roka", "XoRoMu", "ultrakaktus", "Mystery1MSA", "pervuymay", "M1han0vfound", "Drobov", "BongaMan", "dimazz", "Lara"]  # case insensitive
